spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoicemanagment
    password: admin
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: never